---
name: Nuxt App
version: dev
slug: nuxt-app
description: A simple nuxt app
url: https://github.com/Moonlight63/ha-keypad-userdb/tree/main/nuxt
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:shield-check
startup: services
homeassistant: 0.113.2
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
# discovery:
#   - adguard
# auth_api: true
# host_network: true
# hassio_api: true
# hassio_role: manager
map:
  - ssl
  - share:rw
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
