# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Keypad Users Database
version: "1.2.1"
slug: example
description: A simple keystonejs app with a database schema for storing a basic list of users with pincodes, rfid tags, and fingerprints, for use with shell scripts in homeassistant for retreiving the information.
url: "https://github.com/Moonlight63/ha-keypad-userdb/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 3000
# map:
#   - share:rw
ports:
  3000/tcp: 3000
# options:
#   message: "Hello world..."
# schema:
#   message: "str?"
image: "ghcr.io/Moonlight63/{arch}-ha-addon-keypad-users-database"
