---
name: Keypad Users DB
version: 1.0.0
slug: keypad-users
description: A simple webapp to manage credentials for a keypad. Still much to do.
url: https://github.com/Moonlight63/ha-keypad-userdb/tree/main/keypad-users
# codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:shield-check
startup: services
homeassistant: 0.113.2
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
# hassio_api: false
# hassio_role: default
# discovery:
#   - adguard
# auth_api: true
homeassistant_api: true
# host_network: true
# hassio_api: true
# hassio_role: manager
map:
  - ssl
  - share:rw
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  pin_length: 4
  print_length: 6
  rfid_length: 8
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
  pin_length: int
  rfid_length: int
  print_length: int